### ISSUE TITLE
Default template argument for Scalar

### ISSUE THREAD

**Issue by paschalidoud** [angeloskath/supervised-lda#15]

**Comment by angeloskath** [comment]
I added a default value of `double` for LDA, LDABuilder and all the Parameters. @paschalidoud do you think this is enough or we need to add it to more places?

We can now create an LDA as simple as

``` cpp
LDA lda = LDABuilder().initialize_topics_random(100, 10);
```

Do you think it is bad that we hide the ability to use another Scalar type?
